--- #YAML:1.0
name:               Tie-Hash-RegexKeys
version:            1.21
abstract:           Extend Tie::Hash::Regex to retrieve the KEYS in place of values
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tie::Hash::Regex:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
